import type { EditorThemeClasses } from "lexical";

import "./message-theme.css";

const theme: EditorThemeClasses = {
  code: "rich-text__code",
  codeHighlight: {
    atrule: "rich-text__tokenAttr",
    attr: "rich-text__tokenAttr",
    boolean: "rich-text__tokenProperty",
    builtin: "rich-text__tokenSelector",
    cdata: "rich-text__tokenComment",
    char: "rich-text__tokenSelector",
    class: "rich-text__tokenFunction",
    "class-name": "rich-text__tokenFunction",
    comment: "rich-text__tokenComment",
    constant: "rich-text__tokenProperty",
    deleted: "rich-text__tokenProperty",
    doctype: "rich-text__tokenComment",
    entity: "rich-text__tokenOperator",
    function: "rich-text__tokenFunction",
    important: "rich-text__tokenVariable",
    inserted: "rich-text__tokenSelector",
    keyword: "rich-text__tokenAttr",
    namespace: "rich-text__tokenVariable",
    number: "rich-text__tokenProperty",
    operator: "rich-text__tokenOperator",
    prolog: "rich-text__tokenComment",
    property: "rich-text__tokenProperty",
    punctuation: "rich-text__tokenPunctuation",
    regex: "rich-text__tokenVariable",
    selector: "rich-text__tokenSelector",
    string: "rich-text__tokenSelector",
    symbol: "rich-text__tokenProperty",
    tag: "rich-text__tokenProperty",
    url: "rich-text__tokenOperator",
    variable: "rich-text__tokenVariable",
  },
  embedBlock: {
    base: "rich-text__embedBlock",
    focus: "rich-text__embedBlockFocus",
  },
  list: {
    checklist: "rich-text__checklist",
    listitem: "rich-text__listItem",
    listitemChecked: "rich-text__listItemChecked",
    listitemUnchecked: "rich-text__listItemUnchecked",
    nested: {
      listitem: "rich-text__nestedListItem",
    },
    olDepth: ["rich-text__ol1", "rich-text__ol2", "rich-text__ol3", "rich-text__ol4", "rich-text__ol5"],
    ol: "rich-text__ol",
    ul: "rich-text__ul",
  },
  heading: {
    h1: "rich-text__h1",
    h2: "rich-text__h2",
    h3: "rich-text__h3",
  },
  paragraph: "rich-text__p",
  text: {
    underline: "rich-text__textUnderline",
    italic: "rich-text__textItalic",
    code: "rich-text__textCode",
  },
  link: "rich-text__link",
  quote: "rich-text__quote",
  reference: "rich-text__reference",
  table: "rich-text__table",
  tableCell: "rich-text__tableCell",
  tableRow: "rich-text__tableRow",
  tableCellHeader: "rich-text__tableCellHeader",
  layoutContainer: "rich-text__layoutContainer",
  layoutItem: "rich-text__layoutItem",
};

export default theme;
